- name: INSTALL PACKAGES
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: ADDING DOCKER KEY
  become: true
  ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/{{ distr }}/gpg | apt-key add -;

- name: TAKE DISTRO NAME
  ansible.builtin.command:
    cmd: lsb_release -cs
  register: dist

- name: ADDING DOCKER DEB SOURCE
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ distr }} {{ dist.stdout }} stable"
    state: present

- name: UPDATE PACKAGES && INSTALL DOCKER
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-compose
    update_cache: yes
    state: latest
  notify: START DOCKER

- name: COLLECT INFORMATION ABOUT PACKAGES
  ansible.builtin.package_facts:

- name: DOCKER RESULT
  ansible.builtin.debug:
    msg: 
      "DOCKER: {{ ('docker-ce' in ansible_facts.packages) | ternary('Installed Successfully', 'Not installed') }},
      DOCKER-COMPOSE: {{ ('docker-compose' in ansible_facts.packages) | ternary('Installed Successfully', 'Not installed') }}"

- name: DOCKER INSTALLATION FINISHED
  ansible.builtin.pause:
   seconds: 3