---
- name: STOP MARIADB
  become: true
  ansible.builtin.service:
    name: mysql
    state: stopped

- name: START MARIADB
  become: true
  ansible.builtin.service:
    name: mysql
    state: started